#!/bin/dash
. ${HOME}/col/ansi_colors.sh


date_() { date +"%Y.%m.%d"; }
time_() { date +"%l.%M %p"; }
bat_percentage() { cat /sys/class/power_supply/BAT1/capacity; }
disks() { df -h | grep ^/dev | grep -v boot; }
volume() { (amixer get Master | grep -o -e '\w*%' | tr -d %) 2>/dev/null; }
brightness()
{
	current_brgh=$(cat /sys/class/backlight/intel_backlight/brightness)
	max_brgh=$(cat /sys/class/backlight/intel_backlight/max_brightness)
	echo "scale=2; $current_brgh / ($max_brgh / 100)" | bc -l
}
bat_status()
{
	local stat=$(cat /sys/class/power_supply/BAT1/status)
	if [ "$stat" = "Full" ]; then
		printf Full;
	elif [ "$stat" = "Charging" ]; then
		printf Charging;
	elif [ "$stat" = "Discharging" ]; then
		printf Discharging;
	fi
}

echo "$bldcyn\
📅 $(date_)\
$txtrst"
echo "$bldwht\
🕑 $(time_)\
$txtrst"

printf "\n"

echo "$bldblu\
🔉 $(volume)%\
${txtrst}"
echo "$bldylw\
☼  $(brightness)%\
$txtrst" | sed 's/\(.*\)\..*\(%\)/\1\2/'
echo "$bldgrn\
🔋 $(bat_percentage)% $(bat_status)\
$txtrst"

printf "\n"

#printf "Wifi:"
#printf "Vpn:"
#printf "Ethernet:"

disks | while read disk; do
	echo $disk | awk '{printf "'$bldblk'🖫  " $4" '$txtrst'" $6 "\n"}'
done
