#!/bin/sh

bldblk='\033[1;30m' # Black - Bold
bldred='\033[1;31m' # Red
bldgrn='\033[1;32m' # Green
bldylw='\033[1;33m' # Yellow
bldblu='\033[1;34m' # Blue
bldpur='\033[1;35m' # Purple
bldcyn='\033[1;36m' # Cyan
bldwht='\033[1;37m' # White
txtrst='\033[0m'    # Text Reset

#================================================#

date_() { date +"%Y.%m.%d"; }
time_() { date +"%I.%M %p"; }
bat_percentage() { cat /sys/class/power_supply/BAT1/capacity; }
disks() { df -h | grep ^/dev | grep -v boot; }
volume() { (amixer get Master | grep -o -e '\w*%' | tr -d %) 2>/dev/null; }
brightness()
{
	current_brgh=$(cat /sys/class/backlight/intel_backlight/brightness)
	max_brgh=$(cat /sys/class/backlight/intel_backlight/max_brightness)
	echo "scale=2; $current_brgh / ($max_brgh / 100)" | bc -l
}
bat_status()
{
	local stat=$(cat /sys/class/power_supply/BAT1/status)
	if [ "$stat" = "Full" ]; then
		printf Full;
	elif [ "$stat" = "Charging" ]; then
		printf Charging;
	elif [ "$stat" = "Discharging" ]; then
		printf Discharging;
	fi
}

#================================================#

printf "$bldcyn 📅 $(date_) ${txtrst}\n"
printf "$bldwht 🕑 $(time_) ${txtrst}\n"

printf "\n"

printf "$bldblu 🔉 $(volume)%% ${txtrst}\n"
printf "$bldylw ☼  $(brightness)%% $txtrst\n" | sed 's/\(.*\)\..*\(%\)/\1\2/'
printf "$bldgrn 🔋 $(bat_percentage)%% $(bat_status) ${txtrst}\n"

printf "\n"

#TODO
	#printf "Wifi:"
	#printf "Vpn:"
	#printf "Ethernet:"

disks | while read disk; do
	printf "%s\n" "$disk" | awk '{printf "'$bldblk' 🖫  " $4" '$txtrst'" $6 "\n"}'
done
